frase = ("curso em video python")
print(len(frase))
print(frase.count("o", 0, 14))
print(frase.find("c"))
print("curso" in frase)
print(frase.replace("python" , "android"))
print(frase.upper())
print(frase.lower())
print(frase.capitalize())
print(frase.title())
frase2 = ("   Aprendendo Python  ")
print(frase2)
print(frase2.strip())
print(frase2.rstrip())
print(frase2.lstrip())
print(frase.split())
print("-".join(frase))